// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231203163230_user")]
    partial class user
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("P06Shop.Shared.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P06Shop.Shared.SongModel.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlbumTitle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumTitle = "Fresh",
                            Artist = "Ramon Lockman",
                            Duration = 129L,
                            ReleaseDate = new DateTime(2019, 1, 22, 1, 12, 41, 0, DateTimeKind.Local).AddTicks(8714),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            AlbumTitle = "Rubber",
                            Artist = "Leonard Bailey",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2022, 4, 29, 4, 6, 38, 262, DateTimeKind.Local).AddTicks(3439),
                            Title = "Sleek Cotton Shoes"
                        },
                        new
                        {
                            Id = 3,
                            AlbumTitle = "Fresh",
                            Artist = "Dan O'Hara",
                            Duration = 265L,
                            ReleaseDate = new DateTime(2021, 7, 25, 9, 10, 22, 73, DateTimeKind.Local).AddTicks(8622),
                            Title = "Incredible Rubber Bike"
                        },
                        new
                        {
                            Id = 4,
                            AlbumTitle = "Rubber",
                            Artist = "Luther Cruickshank",
                            Duration = 50L,
                            ReleaseDate = new DateTime(2014, 12, 1, 16, 18, 48, 922, DateTimeKind.Local).AddTicks(9302),
                            Title = "Generic Steel Chips"
                        },
                        new
                        {
                            Id = 5,
                            AlbumTitle = "Concrete",
                            Artist = "Alyssa Will",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2014, 6, 11, 14, 16, 44, 594, DateTimeKind.Local).AddTicks(8240),
                            Title = "Generic Granite Shirt"
                        },
                        new
                        {
                            Id = 6,
                            AlbumTitle = "Granite",
                            Artist = "Jaime Veum",
                            Duration = 191L,
                            ReleaseDate = new DateTime(2020, 10, 7, 7, 19, 39, 388, DateTimeKind.Local).AddTicks(5493),
                            Title = "Ergonomic Rubber Bacon"
                        },
                        new
                        {
                            Id = 7,
                            AlbumTitle = "Concrete",
                            Artist = "Tommie Keeling",
                            Duration = 281L,
                            ReleaseDate = new DateTime(2016, 6, 12, 11, 0, 6, 67, DateTimeKind.Local).AddTicks(1864),
                            Title = "Incredible Fresh Soap"
                        },
                        new
                        {
                            Id = 8,
                            AlbumTitle = "Granite",
                            Artist = "Toby Mitchell",
                            Duration = 70L,
                            ReleaseDate = new DateTime(2021, 5, 8, 20, 21, 22, 183, DateTimeKind.Local).AddTicks(1276),
                            Title = "Fantastic Metal Salad"
                        },
                        new
                        {
                            Id = 9,
                            AlbumTitle = "Steel",
                            Artist = "Shari Pacocha",
                            Duration = 40L,
                            ReleaseDate = new DateTime(2021, 6, 27, 0, 9, 31, 880, DateTimeKind.Local).AddTicks(7327),
                            Title = "Sleek Cotton Shirt"
                        },
                        new
                        {
                            Id = 10,
                            AlbumTitle = "Rubber",
                            Artist = "Irvin Weimann",
                            Duration = 237L,
                            ReleaseDate = new DateTime(2022, 4, 28, 18, 32, 20, 202, DateTimeKind.Local).AddTicks(9033),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 11,
                            AlbumTitle = "Granite",
                            Artist = "Elena Schuppe",
                            Duration = 117L,
                            ReleaseDate = new DateTime(2022, 3, 14, 21, 49, 26, 628, DateTimeKind.Local).AddTicks(1310),
                            Title = "Licensed Soft Tuna"
                        },
                        new
                        {
                            Id = 12,
                            AlbumTitle = "Soft",
                            Artist = "Clara Gleichner",
                            Duration = 158L,
                            ReleaseDate = new DateTime(2021, 11, 2, 8, 29, 7, 659, DateTimeKind.Local).AddTicks(389),
                            Title = "Tasty Plastic Shirt"
                        },
                        new
                        {
                            Id = 13,
                            AlbumTitle = "Rubber",
                            Artist = "Gloria Kutch",
                            Duration = 105L,
                            ReleaseDate = new DateTime(2015, 11, 24, 0, 21, 39, 537, DateTimeKind.Local).AddTicks(4969),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 14,
                            AlbumTitle = "Fresh",
                            Artist = "Tracy Harris",
                            Duration = 124L,
                            ReleaseDate = new DateTime(2023, 5, 13, 11, 10, 28, 54, DateTimeKind.Local).AddTicks(3124),
                            Title = "Sleek Frozen Mouse"
                        },
                        new
                        {
                            Id = 15,
                            AlbumTitle = "Rubber",
                            Artist = "Alexander Hoppe",
                            Duration = 117L,
                            ReleaseDate = new DateTime(2015, 5, 22, 4, 45, 49, 553, DateTimeKind.Local).AddTicks(2627),
                            Title = "Rustic Plastic Car"
                        },
                        new
                        {
                            Id = 16,
                            AlbumTitle = "Soft",
                            Artist = "Jesse Bartell",
                            Duration = 204L,
                            ReleaseDate = new DateTime(2016, 10, 9, 8, 37, 54, 985, DateTimeKind.Local).AddTicks(6902),
                            Title = "Tasty Frozen Pants"
                        },
                        new
                        {
                            Id = 17,
                            AlbumTitle = "Fresh",
                            Artist = "Carroll Orn",
                            Duration = 163L,
                            ReleaseDate = new DateTime(2018, 9, 29, 19, 1, 58, 567, DateTimeKind.Local).AddTicks(8559),
                            Title = "Generic Steel Tuna"
                        },
                        new
                        {
                            Id = 18,
                            AlbumTitle = "Steel",
                            Artist = "Helen Pagac",
                            Duration = 60L,
                            ReleaseDate = new DateTime(2019, 3, 9, 8, 5, 19, 988, DateTimeKind.Local).AddTicks(1847),
                            Title = "Generic Metal Table"
                        },
                        new
                        {
                            Id = 19,
                            AlbumTitle = "Wooden",
                            Artist = "Antonio Predovic",
                            Duration = 269L,
                            ReleaseDate = new DateTime(2020, 9, 18, 2, 10, 57, 810, DateTimeKind.Local).AddTicks(8855),
                            Title = "Handmade Metal Gloves"
                        },
                        new
                        {
                            Id = 20,
                            AlbumTitle = "Wooden",
                            Artist = "Gerard Jast",
                            Duration = 151L,
                            ReleaseDate = new DateTime(2023, 3, 14, 15, 13, 50, 476, DateTimeKind.Local).AddTicks(651),
                            Title = "Intelligent Concrete Chips"
                        },
                        new
                        {
                            Id = 21,
                            AlbumTitle = "Metal",
                            Artist = "Don Rau",
                            Duration = 134L,
                            ReleaseDate = new DateTime(2016, 8, 20, 15, 18, 2, 521, DateTimeKind.Local).AddTicks(8973),
                            Title = "Small Plastic Keyboard"
                        },
                        new
                        {
                            Id = 22,
                            AlbumTitle = "Wooden",
                            Artist = "Glenda Ortiz",
                            Duration = 217L,
                            ReleaseDate = new DateTime(2022, 6, 21, 11, 33, 31, 448, DateTimeKind.Local).AddTicks(5855),
                            Title = "Small Soft Chips"
                        },
                        new
                        {
                            Id = 23,
                            AlbumTitle = "Frozen",
                            Artist = "Traci McGlynn",
                            Duration = 73L,
                            ReleaseDate = new DateTime(2021, 6, 9, 9, 2, 59, 357, DateTimeKind.Local).AddTicks(2851),
                            Title = "Awesome Plastic Gloves"
                        },
                        new
                        {
                            Id = 24,
                            AlbumTitle = "Metal",
                            Artist = "Lola Hudson",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2023, 1, 19, 2, 44, 36, 181, DateTimeKind.Local).AddTicks(7305),
                            Title = "Handmade Rubber Car"
                        },
                        new
                        {
                            Id = 25,
                            AlbumTitle = "Rubber",
                            Artist = "Alberta Hickle",
                            Duration = 128L,
                            ReleaseDate = new DateTime(2020, 10, 12, 9, 52, 37, 992, DateTimeKind.Local).AddTicks(6032),
                            Title = "Small Concrete Hat"
                        },
                        new
                        {
                            Id = 26,
                            AlbumTitle = "Plastic",
                            Artist = "Terri Rippin",
                            Duration = 96L,
                            ReleaseDate = new DateTime(2022, 1, 12, 21, 6, 6, 685, DateTimeKind.Local).AddTicks(2225),
                            Title = "Gorgeous Granite Bacon"
                        },
                        new
                        {
                            Id = 27,
                            AlbumTitle = "Steel",
                            Artist = "Kelly Farrell",
                            Duration = 188L,
                            ReleaseDate = new DateTime(2014, 8, 11, 13, 4, 55, 385, DateTimeKind.Local).AddTicks(7841),
                            Title = "Practical Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            AlbumTitle = "Plastic",
                            Artist = "Marta Rutherford",
                            Duration = 45L,
                            ReleaseDate = new DateTime(2016, 3, 26, 13, 39, 54, 393, DateTimeKind.Local).AddTicks(1657),
                            Title = "Refined Steel Gloves"
                        },
                        new
                        {
                            Id = 29,
                            AlbumTitle = "Steel",
                            Artist = "Yvette Bashirian",
                            Duration = 181L,
                            ReleaseDate = new DateTime(2017, 12, 29, 7, 36, 6, 823, DateTimeKind.Local).AddTicks(9720),
                            Title = "Handmade Rubber Pants"
                        },
                        new
                        {
                            Id = 30,
                            AlbumTitle = "Soft",
                            Artist = "Santos Tremblay",
                            Duration = 35L,
                            ReleaseDate = new DateTime(2022, 4, 12, 17, 9, 45, 915, DateTimeKind.Local).AddTicks(6449),
                            Title = "Licensed Rubber Shirt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
