// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231202211504_UsersMigration")]
    partial class UsersMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("P06Shop.Shared.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("P06Shop.Shared.SongModel.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlbumTitle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumTitle = "Fresh",
                            Artist = "Ramon Lockman",
                            Duration = 129L,
                            ReleaseDate = new DateTime(2019, 1, 21, 4, 55, 15, 223, DateTimeKind.Local).AddTicks(7501),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            AlbumTitle = "Rubber",
                            Artist = "Leonard Bailey",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2022, 4, 28, 7, 49, 12, 485, DateTimeKind.Local).AddTicks(841),
                            Title = "Sleek Cotton Shoes"
                        },
                        new
                        {
                            Id = 3,
                            AlbumTitle = "Fresh",
                            Artist = "Dan O'Hara",
                            Duration = 265L,
                            ReleaseDate = new DateTime(2021, 7, 24, 12, 52, 56, 296, DateTimeKind.Local).AddTicks(4801),
                            Title = "Incredible Rubber Bike"
                        },
                        new
                        {
                            Id = 4,
                            AlbumTitle = "Rubber",
                            Artist = "Luther Cruickshank",
                            Duration = 50L,
                            ReleaseDate = new DateTime(2014, 11, 30, 20, 1, 23, 145, DateTimeKind.Local).AddTicks(6032),
                            Title = "Generic Steel Chips"
                        },
                        new
                        {
                            Id = 5,
                            AlbumTitle = "Concrete",
                            Artist = "Alyssa Will",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2014, 6, 10, 17, 59, 18, 817, DateTimeKind.Local).AddTicks(4888),
                            Title = "Generic Granite Shirt"
                        },
                        new
                        {
                            Id = 6,
                            AlbumTitle = "Granite",
                            Artist = "Jaime Veum",
                            Duration = 191L,
                            ReleaseDate = new DateTime(2020, 10, 6, 11, 2, 13, 611, DateTimeKind.Local).AddTicks(1989),
                            Title = "Ergonomic Rubber Bacon"
                        },
                        new
                        {
                            Id = 7,
                            AlbumTitle = "Concrete",
                            Artist = "Tommie Keeling",
                            Duration = 281L,
                            ReleaseDate = new DateTime(2016, 6, 11, 14, 42, 40, 289, DateTimeKind.Local).AddTicks(8306),
                            Title = "Incredible Fresh Soap"
                        },
                        new
                        {
                            Id = 8,
                            AlbumTitle = "Granite",
                            Artist = "Toby Mitchell",
                            Duration = 70L,
                            ReleaseDate = new DateTime(2021, 5, 8, 0, 3, 56, 405, DateTimeKind.Local).AddTicks(7597),
                            Title = "Fantastic Metal Salad"
                        },
                        new
                        {
                            Id = 9,
                            AlbumTitle = "Steel",
                            Artist = "Shari Pacocha",
                            Duration = 40L,
                            ReleaseDate = new DateTime(2021, 6, 26, 3, 52, 6, 103, DateTimeKind.Local).AddTicks(3525),
                            Title = "Sleek Cotton Shirt"
                        },
                        new
                        {
                            Id = 10,
                            AlbumTitle = "Rubber",
                            Artist = "Irvin Weimann",
                            Duration = 237L,
                            ReleaseDate = new DateTime(2022, 4, 27, 22, 14, 54, 425, DateTimeKind.Local).AddTicks(5279),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 11,
                            AlbumTitle = "Granite",
                            Artist = "Elena Schuppe",
                            Duration = 117L,
                            ReleaseDate = new DateTime(2022, 3, 14, 1, 32, 0, 850, DateTimeKind.Local).AddTicks(7495),
                            Title = "Licensed Soft Tuna"
                        },
                        new
                        {
                            Id = 12,
                            AlbumTitle = "Soft",
                            Artist = "Clara Gleichner",
                            Duration = 158L,
                            ReleaseDate = new DateTime(2021, 11, 1, 12, 11, 41, 881, DateTimeKind.Local).AddTicks(6535),
                            Title = "Tasty Plastic Shirt"
                        },
                        new
                        {
                            Id = 13,
                            AlbumTitle = "Rubber",
                            Artist = "Gloria Kutch",
                            Duration = 105L,
                            ReleaseDate = new DateTime(2015, 11, 23, 4, 4, 13, 760, DateTimeKind.Local).AddTicks(1127),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 14,
                            AlbumTitle = "Fresh",
                            Artist = "Tracy Harris",
                            Duration = 124L,
                            ReleaseDate = new DateTime(2023, 5, 12, 14, 53, 2, 276, DateTimeKind.Local).AddTicks(9236),
                            Title = "Sleek Frozen Mouse"
                        },
                        new
                        {
                            Id = 15,
                            AlbumTitle = "Rubber",
                            Artist = "Alexander Hoppe",
                            Duration = 117L,
                            ReleaseDate = new DateTime(2015, 5, 21, 8, 28, 23, 775, DateTimeKind.Local).AddTicks(8704),
                            Title = "Rustic Plastic Car"
                        },
                        new
                        {
                            Id = 16,
                            AlbumTitle = "Soft",
                            Artist = "Jesse Bartell",
                            Duration = 204L,
                            ReleaseDate = new DateTime(2016, 10, 8, 12, 20, 29, 208, DateTimeKind.Local).AddTicks(3036),
                            Title = "Tasty Frozen Pants"
                        },
                        new
                        {
                            Id = 17,
                            AlbumTitle = "Fresh",
                            Artist = "Carroll Orn",
                            Duration = 163L,
                            ReleaseDate = new DateTime(2018, 9, 28, 22, 44, 32, 790, DateTimeKind.Local).AddTicks(4683),
                            Title = "Generic Steel Tuna"
                        },
                        new
                        {
                            Id = 18,
                            AlbumTitle = "Steel",
                            Artist = "Helen Pagac",
                            Duration = 60L,
                            ReleaseDate = new DateTime(2019, 3, 8, 11, 47, 54, 210, DateTimeKind.Local).AddTicks(7978),
                            Title = "Generic Metal Table"
                        },
                        new
                        {
                            Id = 19,
                            AlbumTitle = "Wooden",
                            Artist = "Antonio Predovic",
                            Duration = 269L,
                            ReleaseDate = new DateTime(2020, 9, 17, 5, 53, 32, 33, DateTimeKind.Local).AddTicks(5105),
                            Title = "Handmade Metal Gloves"
                        },
                        new
                        {
                            Id = 20,
                            AlbumTitle = "Wooden",
                            Artist = "Gerard Jast",
                            Duration = 151L,
                            ReleaseDate = new DateTime(2023, 3, 13, 18, 56, 24, 698, DateTimeKind.Local).AddTicks(7076),
                            Title = "Intelligent Concrete Chips"
                        },
                        new
                        {
                            Id = 21,
                            AlbumTitle = "Metal",
                            Artist = "Don Rau",
                            Duration = 134L,
                            ReleaseDate = new DateTime(2016, 8, 19, 19, 0, 36, 744, DateTimeKind.Local).AddTicks(5463),
                            Title = "Small Plastic Keyboard"
                        },
                        new
                        {
                            Id = 22,
                            AlbumTitle = "Wooden",
                            Artist = "Glenda Ortiz",
                            Duration = 217L,
                            ReleaseDate = new DateTime(2022, 6, 20, 15, 16, 5, 671, DateTimeKind.Local).AddTicks(2441),
                            Title = "Small Soft Chips"
                        },
                        new
                        {
                            Id = 23,
                            AlbumTitle = "Frozen",
                            Artist = "Traci McGlynn",
                            Duration = 73L,
                            ReleaseDate = new DateTime(2021, 6, 8, 12, 45, 33, 579, DateTimeKind.Local).AddTicks(9421),
                            Title = "Awesome Plastic Gloves"
                        },
                        new
                        {
                            Id = 24,
                            AlbumTitle = "Metal",
                            Artist = "Lola Hudson",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2023, 1, 18, 6, 27, 10, 404, DateTimeKind.Local).AddTicks(3825),
                            Title = "Handmade Rubber Car"
                        },
                        new
                        {
                            Id = 25,
                            AlbumTitle = "Rubber",
                            Artist = "Alberta Hickle",
                            Duration = 128L,
                            ReleaseDate = new DateTime(2020, 10, 11, 13, 35, 12, 215, DateTimeKind.Local).AddTicks(1725),
                            Title = "Small Concrete Hat"
                        },
                        new
                        {
                            Id = 26,
                            AlbumTitle = "Plastic",
                            Artist = "Terri Rippin",
                            Duration = 96L,
                            ReleaseDate = new DateTime(2022, 1, 12, 0, 48, 40, 907, DateTimeKind.Local).AddTicks(7011),
                            Title = "Gorgeous Granite Bacon"
                        },
                        new
                        {
                            Id = 27,
                            AlbumTitle = "Steel",
                            Artist = "Kelly Farrell",
                            Duration = 188L,
                            ReleaseDate = new DateTime(2014, 8, 10, 16, 47, 29, 608, DateTimeKind.Local).AddTicks(2252),
                            Title = "Practical Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            AlbumTitle = "Plastic",
                            Artist = "Marta Rutherford",
                            Duration = 45L,
                            ReleaseDate = new DateTime(2016, 3, 25, 17, 22, 28, 615, DateTimeKind.Local).AddTicks(6435),
                            Title = "Refined Steel Gloves"
                        },
                        new
                        {
                            Id = 29,
                            AlbumTitle = "Steel",
                            Artist = "Yvette Bashirian",
                            Duration = 181L,
                            ReleaseDate = new DateTime(2017, 12, 28, 11, 18, 41, 46, DateTimeKind.Local).AddTicks(4903),
                            Title = "Handmade Rubber Pants"
                        },
                        new
                        {
                            Id = 30,
                            AlbumTitle = "Soft",
                            Artist = "Santos Tremblay",
                            Duration = 35L,
                            ReleaseDate = new DateTime(2022, 4, 11, 20, 52, 20, 138, DateTimeKind.Local).AddTicks(2077),
                            Title = "Licensed Rubber Shirt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
