// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231126111216_InitialSong")]
    partial class InitialSong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("P06Shop.Shared.SongModel.Song", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AlbumTitle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AlbumTitle = "Fresh",
                            Artist = "Ramon Lockman",
                            Duration = 129L,
                            ReleaseDate = new DateTime(2019, 1, 14, 18, 52, 26, 726, DateTimeKind.Local).AddTicks(1390),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2L,
                            AlbumTitle = "Rubber",
                            Artist = "Leonard Bailey",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2022, 4, 21, 21, 46, 23, 987, DateTimeKind.Local).AddTicks(4310),
                            Title = "Sleek Cotton Shoes"
                        },
                        new
                        {
                            Id = 3L,
                            AlbumTitle = "Fresh",
                            Artist = "Dan O'Hara",
                            Duration = 265L,
                            ReleaseDate = new DateTime(2021, 7, 18, 2, 50, 7, 798, DateTimeKind.Local).AddTicks(8057),
                            Title = "Incredible Rubber Bike"
                        },
                        new
                        {
                            Id = 4L,
                            AlbumTitle = "Rubber",
                            Artist = "Luther Cruickshank",
                            Duration = 50L,
                            ReleaseDate = new DateTime(2014, 11, 24, 9, 58, 34, 647, DateTimeKind.Local).AddTicks(8463),
                            Title = "Generic Steel Chips"
                        },
                        new
                        {
                            Id = 5L,
                            AlbumTitle = "Concrete",
                            Artist = "Alyssa Will",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2014, 6, 4, 7, 56, 30, 319, DateTimeKind.Local).AddTicks(7809),
                            Title = "Generic Granite Shirt"
                        },
                        new
                        {
                            Id = 6L,
                            AlbumTitle = "Granite",
                            Artist = "Jaime Veum",
                            Duration = 191L,
                            ReleaseDate = new DateTime(2020, 9, 30, 0, 59, 25, 113, DateTimeKind.Local).AddTicks(4814),
                            Title = "Ergonomic Rubber Bacon"
                        },
                        new
                        {
                            Id = 7L,
                            AlbumTitle = "Concrete",
                            Artist = "Tommie Keeling",
                            Duration = 281L,
                            ReleaseDate = new DateTime(2016, 6, 5, 4, 39, 51, 792, DateTimeKind.Local).AddTicks(956),
                            Title = "Incredible Fresh Soap"
                        },
                        new
                        {
                            Id = 8L,
                            AlbumTitle = "Granite",
                            Artist = "Toby Mitchell",
                            Duration = 70L,
                            ReleaseDate = new DateTime(2021, 5, 1, 14, 1, 7, 908, DateTimeKind.Local).AddTicks(312),
                            Title = "Fantastic Metal Salad"
                        },
                        new
                        {
                            Id = 9L,
                            AlbumTitle = "Steel",
                            Artist = "Shari Pacocha",
                            Duration = 40L,
                            ReleaseDate = new DateTime(2021, 6, 19, 17, 49, 17, 605, DateTimeKind.Local).AddTicks(6152),
                            Title = "Sleek Cotton Shirt"
                        },
                        new
                        {
                            Id = 10L,
                            AlbumTitle = "Rubber",
                            Artist = "Irvin Weimann",
                            Duration = 237L,
                            ReleaseDate = new DateTime(2022, 4, 21, 12, 12, 5, 927, DateTimeKind.Local).AddTicks(7743),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 11L,
                            AlbumTitle = "Granite",
                            Artist = "Elena Schuppe",
                            Duration = 117L,
                            ReleaseDate = new DateTime(2022, 3, 7, 15, 29, 12, 353, DateTimeKind.Local).AddTicks(23),
                            Title = "Licensed Soft Tuna"
                        },
                        new
                        {
                            Id = 12L,
                            AlbumTitle = "Soft",
                            Artist = "Clara Gleichner",
                            Duration = 158L,
                            ReleaseDate = new DateTime(2021, 10, 26, 2, 8, 53, 383, DateTimeKind.Local).AddTicks(9041),
                            Title = "Tasty Plastic Shirt"
                        },
                        new
                        {
                            Id = 13L,
                            AlbumTitle = "Rubber",
                            Artist = "Gloria Kutch",
                            Duration = 105L,
                            ReleaseDate = new DateTime(2015, 11, 16, 18, 1, 25, 262, DateTimeKind.Local).AddTicks(3559),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 14L,
                            AlbumTitle = "Fresh",
                            Artist = "Tracy Harris",
                            Duration = 124L,
                            ReleaseDate = new DateTime(2023, 5, 6, 4, 50, 13, 779, DateTimeKind.Local).AddTicks(1730),
                            Title = "Sleek Frozen Mouse"
                        },
                        new
                        {
                            Id = 15L,
                            AlbumTitle = "Rubber",
                            Artist = "Alexander Hoppe",
                            Duration = 117L,
                            ReleaseDate = new DateTime(2015, 5, 14, 22, 25, 35, 278, DateTimeKind.Local).AddTicks(1041),
                            Title = "Rustic Plastic Car"
                        },
                        new
                        {
                            Id = 16L,
                            AlbumTitle = "Soft",
                            Artist = "Jesse Bartell",
                            Duration = 204L,
                            ReleaseDate = new DateTime(2016, 10, 2, 2, 17, 40, 710, DateTimeKind.Local).AddTicks(5174),
                            Title = "Tasty Frozen Pants"
                        },
                        new
                        {
                            Id = 17L,
                            AlbumTitle = "Fresh",
                            Artist = "Carroll Orn",
                            Duration = 163L,
                            ReleaseDate = new DateTime(2018, 9, 22, 12, 41, 44, 292, DateTimeKind.Local).AddTicks(6809),
                            Title = "Generic Steel Tuna"
                        },
                        new
                        {
                            Id = 18L,
                            AlbumTitle = "Steel",
                            Artist = "Helen Pagac",
                            Duration = 60L,
                            ReleaseDate = new DateTime(2019, 3, 2, 1, 45, 5, 712, DateTimeKind.Local).AddTicks(9994),
                            Title = "Generic Metal Table"
                        },
                        new
                        {
                            Id = 19L,
                            AlbumTitle = "Wooden",
                            Artist = "Antonio Predovic",
                            Duration = 269L,
                            ReleaseDate = new DateTime(2020, 9, 10, 19, 50, 43, 535, DateTimeKind.Local).AddTicks(6893),
                            Title = "Handmade Metal Gloves"
                        },
                        new
                        {
                            Id = 20L,
                            AlbumTitle = "Wooden",
                            Artist = "Gerard Jast",
                            Duration = 151L,
                            ReleaseDate = new DateTime(2023, 3, 7, 8, 53, 36, 200, DateTimeKind.Local).AddTicks(8712),
                            Title = "Intelligent Concrete Chips"
                        },
                        new
                        {
                            Id = 21L,
                            AlbumTitle = "Metal",
                            Artist = "Don Rau",
                            Duration = 134L,
                            ReleaseDate = new DateTime(2016, 8, 13, 8, 57, 48, 246, DateTimeKind.Local).AddTicks(6946),
                            Title = "Small Plastic Keyboard"
                        },
                        new
                        {
                            Id = 22L,
                            AlbumTitle = "Wooden",
                            Artist = "Glenda Ortiz",
                            Duration = 217L,
                            ReleaseDate = new DateTime(2022, 6, 14, 5, 13, 17, 173, DateTimeKind.Local).AddTicks(3762),
                            Title = "Small Soft Chips"
                        },
                        new
                        {
                            Id = 23L,
                            AlbumTitle = "Frozen",
                            Artist = "Traci McGlynn",
                            Duration = 73L,
                            ReleaseDate = new DateTime(2021, 6, 2, 2, 42, 45, 82, DateTimeKind.Local).AddTicks(785),
                            Title = "Awesome Plastic Gloves"
                        },
                        new
                        {
                            Id = 24L,
                            AlbumTitle = "Metal",
                            Artist = "Lola Hudson",
                            Duration = 101L,
                            ReleaseDate = new DateTime(2023, 1, 11, 20, 24, 21, 906, DateTimeKind.Local).AddTicks(5156),
                            Title = "Handmade Rubber Car"
                        },
                        new
                        {
                            Id = 25L,
                            AlbumTitle = "Rubber",
                            Artist = "Alberta Hickle",
                            Duration = 128L,
                            ReleaseDate = new DateTime(2020, 10, 5, 3, 32, 23, 717, DateTimeKind.Local).AddTicks(2937),
                            Title = "Small Concrete Hat"
                        },
                        new
                        {
                            Id = 26L,
                            AlbumTitle = "Plastic",
                            Artist = "Terri Rippin",
                            Duration = 96L,
                            ReleaseDate = new DateTime(2022, 1, 5, 14, 45, 52, 409, DateTimeKind.Local).AddTicks(7966),
                            Title = "Gorgeous Granite Bacon"
                        },
                        new
                        {
                            Id = 27L,
                            AlbumTitle = "Steel",
                            Artist = "Kelly Farrell",
                            Duration = 188L,
                            ReleaseDate = new DateTime(2014, 8, 4, 6, 44, 41, 110, DateTimeKind.Local).AddTicks(2922),
                            Title = "Practical Plastic Chips"
                        },
                        new
                        {
                            Id = 28L,
                            AlbumTitle = "Plastic",
                            Artist = "Marta Rutherford",
                            Duration = 45L,
                            ReleaseDate = new DateTime(2016, 3, 19, 7, 19, 40, 117, DateTimeKind.Local).AddTicks(6634),
                            Title = "Refined Steel Gloves"
                        },
                        new
                        {
                            Id = 29L,
                            AlbumTitle = "Steel",
                            Artist = "Yvette Bashirian",
                            Duration = 181L,
                            ReleaseDate = new DateTime(2017, 12, 22, 1, 15, 52, 548, DateTimeKind.Local).AddTicks(4617),
                            Title = "Handmade Rubber Pants"
                        },
                        new
                        {
                            Id = 30L,
                            AlbumTitle = "Soft",
                            Artist = "Santos Tremblay",
                            Duration = 35L,
                            ReleaseDate = new DateTime(2022, 4, 5, 10, 49, 31, 640, DateTimeKind.Local).AddTicks(1162),
                            Title = "Licensed Rubber Shirt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
